import Head from 'next/head'
import Image from 'next/image'
import photo from '../assets/images/photo.jpg'
import photo1 from '../assets/images/photo1.jpg'
import photo2 from '../assets/images/photo2.jpg'
import photo3 from '../assets/images/photo3.jpg'
import photo4 from '../assets/images/photo4.jpg'
import photo5 from '../assets/images/photo5.jpg'
import photo6 from '../assets/images/photo6.jpg'
import photo7 from '../assets/images/photo7.jpg'
import photo8 from '../assets/images/photo8.jpg'
import photo9 from '../assets/images/photo9.jpg'
import photo10 from '../assets/images/photo10.jpg'
import photo11 from '../assets/images/photo11.jpg'
import portrait from '../assets/images/portrait.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <div className='h-50 w-full px-4 py-8 mx-auto items-center bg-cover bg-[url("../assets/images/bg.jpg")]'>
            <div className='text-center p-10 text-white'>
              <h1 className='text-5xl font-medium'>John Doe</h1>
              <h2 className='text-2xl'>Photographer</h2>
            {/* <Image className='w-full object-cover' src={bg} alt=''/>   */}
            </div>
          </div>
        </section>
        <section>
          <div className='container px-4 py-8 mx-auto items-center'>
            <div className='grid grid-cols-2 gap-4'>
              <div className='text-left'>
                <h2 id='about' className='text-2xl pb-4'>About The Photographer</h2>
                <p>Nulla placerat sagittis lacinia. Phasellus sollicitudin mollis rhoncus. Nam a tristique elit. In dignissim vulputate nisi ac hendrerit. Mauris non augue nec est cursus ultrices. Donec lacinia tempor porta. Etiam nunc elit, imperdiet in quam vitae, faucibus lobortis sapien. Quisque sodales sit amet velit vitae convallis. Maecenas quis consequat libero. Duis iaculis libero non sapien imperdiet gravida in a quam. Mauris in mi in est porttitor dignissim a at urna. Nam varius in quam non tincidunt.</p>
              </div>
              <div>
                <Image className='w-full object-cover rounded-lg' src={portrait} alt='' placeholder='blur' />
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className='container px-4 py-8 mx-auto items-center'>
            <div className='text-left pb-4'>
              <h2 id='portfolio' className='text-2xl'>My Work</h2>
            </div>
            <div className='grid grid-rows-4 grid-flow-col-dense gap-1'>
              <div className='w-full col-span-2 row-span-2'>
                <Image className='w-full object-cover rounded-lg' src={photo} alt='' placeholder='blur' />
              </div>
              <div className='w-full col-span-2'>
                <Image className='w-full object-cover rounded-lg' src={photo1} alt='' placeholder='blur' />
              </div>
              <div className='w-full'>
                <Image className='w-full object-cover rounded-lg' src={photo2} alt='' placeholder='blur' />
              </div>
              <div className='w-full'>
                <Image className='w-full object-cover rounded-lg' src={photo3} alt='' placeholder='blur' />
              </div>
              <div className='w-full col-span-2'>
                <Image className='w-full object-cover rounded-lg' src={photo4} alt='' placeholder='blur' />
              </div>
              <div className='w-full'>
                <Image className='w-full object-cover rounded-lg' src={photo5} alt='' placeholder='blur' />
              </div>
              <div className='w-full col-span-2 row-span-2'>
                <Image className='w-full object-cover rounded-lg' src={photo6} alt='' placeholder='blur' />
              </div>
              <div className='w-full'>
                <Image className='w-full object-cover rounded-lg' src={photo7} alt='' placeholder='blur' />
              </div>
              <div className='w-full'>
                <Image className='w-full object-cover rounded-lg' src={photo8} alt='' placeholder='blur' />
              </div>
              <div className='w-full '>
                <Image className='w-full object-cover rounded-lg' src={photo9} alt='' placeholder='blur' />
              </div>
              <div className='w-full '>
                <Image className='w-full object-cover rounded-lg' src={photo10} alt='' placeholder='blur' />
              </div>
              <div className='w-full '>
                <Image className='w-full object-cover rounded-lg' src={photo11} alt='' placeholder='blur' />
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className='container px-4 py-8 mx-auto items-center'>
            <h2 id='contact' className='text-2xl pb-4'>Contact Me</h2>
            <div className='shadow-lg p-10 rounded-lg'>
              <form className=''>
                <label>Name</label>
                <input className='border w-full my-2 h-10 rounded-lg p-4' placeholder='John Doe'/>
                <label>Email</label>
                <input className='border w-full my-2 h-10 rounded-lg p-4' placeholder='example@domain.com' />
                <label>Message</label>
                <textarea className='border my-2 h-40 w-full rounded-lg p-4' placeholder='Enter a message...' />
                <button className='bg-black text-white py-2 px-2 right hover:bg-gray-600 hover:text-white hover:shadow-inner'>
                  Hire Me
                </button>
              </form>
            </div>
          </div>
        </section>

        <section>
          <div className='container px-4 py-8 mx-auto items-center'>
            <footer className=''>
              
            </footer>
          </div>
        </section>

      </main>
    </>
  )
}
